kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "vesta.fullname" . }}-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: {{ include "vesta.fullname" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-clusterrole
  apiGroup: rbac.authorization.k8s.io